### ISSUE TITLE
implicit conversion std::string->std::wstring

### ISSUE THREAD

**Issue by Swipes13** [BicycleStudio/Ewe#100]
На данный момент используется аналог explicit через статическую функцию, описанную в utils. 
```c++
std::string str = "";
auto wstr = utils::getWstring(str);
```
Необходимо получить:
```c++
std::string str = "";
std::wstring wstr = str;
```

**Comment by Telhar** [comment]
оператор = нельзя переопределить вне класса, но можно определить другие операторы.
http://en.cppreference.com/w/cpp/language/operator_assignment
например, можно использовать `%=`.
