### ISSUE TITLE
реализовать библиотеку для работы с Win32API

### ISSUE THREAD

**Issue by Telhar** [BicycleStudio/Ewe#6]
* создание и удаление окна
* работа с системными прерываниями
...

**Comment by Swipes13** [comment]
Библиотека system. 
Сущность WindowFacade.
* обработка прерываний(превращение в команды)
 * сворачивание/разворачивание окна [Pause/Unpause -> all]
 * изменение размера окна [SizeChange -> Graphic]
 * нажатие на крестик [Kill -> all]
* подготовка HWND (абстракции) для Graphic и IO

**Comment by Swipes13** [comment]
Сообщения 
* сворачивание/разворачивание окна [Pause/Unpause -> all] (-)
* нажатие на крестик [Kill -> all] (+)
будем отсылать ThreadManager'у, а он будет выполнять для всех соответственно pause()/resume() или stop().
